:bug; Summaryの取り扱いを修正

diff --git a/.github/workflows/ShowDeployLog.yaml b/.github/workflows/ShowDeployLog.yaml
--- a/.github/workflows/ShowDeployLog.yaml
+++ b/.github/workflows/ShowDeployLog.yaml
@@ -16,20 +16,18 @@ jobs:
         run: vercel link --token=${{secrets.VERCEL_TOKEN}} --project ${{vars.VERCEL_PROJECT}} --yes
       - name: Get Vercel Deploy Log
         run: |
-          vercel inspect ${{ github.event.inputs.vercel-deploy-url }} --logs --token=${{secrets.VERCEL_TOKEN}} >deploy-log.txt 2>deploy-log.txt
-        continue-on-error: true
+          vercel inspect ${{ github.event.inputs.vercel-deploy-url }} --logs --token=${{secrets.VERCEL_TOKEN}} > deploy-log.txt || echo "Failed to fetch logs." > deploy-log.txt
+        continue-on-error: true     
       - name: Create Summary File
         id: create-summary
         run: |
-          cat  << EOF > summary.md
-          ## :rocket: Vercel Deploy Log
-          ```
-          $(cat deploy-log.txt)
-          ```
-          EOF
-          echo summary=$(cat summary.md) >> $GITHUB_ENV
-      - name:  Write a summary
+          echo "## :rocket: Vercel Deploy Log" > summary.md
+          echo '```' >> summary.md
+          cat deploy-log.txt >> summary.md
+          echo '```' >> summary.md 
+
+          echo summary="## :rocket: Vercel Deploy Log\n\`\`\`\n$(cat deploy-log.txt)\n\`\`\`" >> $GITHUB_ENV
+      - name: Write a summary
         uses: ./.github/actions/write-summary
         with:
-          message: ${{ steps.create-summary.outputs.summary }}
-            
+          message: ${{ env.summary }}
